language: crystal
sudo: required
crystal:
    - latest
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gsl-bin libgsl0-dbg libgsl0-dev libgsl0ldbl libatlas-base-dev
install:
  - shards install
script:
  - crystal tool format --check
  - crystal build --link-flags "-lgsl -lcblas -lgslcblas -lm -lpcre -lm -lgc -lpthread -levent -ldl -L/usr/lib -L/usr/local/lib" ./src/gsl.cr
  - crystal spec
