language: crystal
sudo: required
crystal:
    - latest
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gsl-bin libgsl-dbg libgsl-dev libatlas-base-dev
install:
  - shards install
script:
  - crystal tool format --check
  - crystal build ./src/gsl.cr
  - crystal spec
