name: Linux CI

on:
  - push
  - pull_request
  - schedule:
      - cron: "0 6 * * 6"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, crystal: latest }
          - { os: ubuntu-latest, crystal: nightly }
    runs-on: ${{matrix.os}}
    steps:
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install libatlas-base-dev libgsl-dev
      - run: shards install
      - run: crystal spec
      - run: crystal tool format && git diff --exit-code
