name: Windows CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 6"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: oprypin/install-crystal@v1
      - uses: actions/checkout@v2
      - name: Cache GSL binaries
        id: cache-gsl
        uses: actions/cache@v2
        with:
          path: |
            gsl/lib/x64/Debug/gsl.lib
            gsl/lib/x64/Debug/cblas.lib
          key: static-x64-Debug-78fd965ff426117fa9a250365f6d4525fa7808e0
      - name: Checkout GSL
        if: steps.cache-gsl.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: BrianGladman/gsl
          path: gsl
          ref: 78fd965ff426117fa9a250365f6d4525fa7808e0 # master @ 2024-06-19
      - name: Add msbuild to PATH
        if: steps.cache-gsl.outputs.cache-hit != 'true'
        uses: microsoft/setup-msbuild@v1.1
      - name: compile GSL
        if: steps.cache-gsl.outputs.cache-hit != 'true'
        run: |
          cd gsl
          cd build.vc
          msbuild gslhdrs/gslhdrs.vcxproj /p:Configuration=Debug /p:Platform=x64
          msbuild gsl.lib.sln /p:Configuration=Debug /p:Platform=x64
      - name: copy GSL libraries
        run: |
          echo "LIB=$(pwd)\gsl/lib/x64/Debug;${env:LIB}" >>${env:GITHUB_ENV}
      - run: shards install
      - run: crystal spec
